# Generated by Django 4.2.10 on 2026-04-06 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField()),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('source_type', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('related_tickers', models.JSONField(default=list)),
                ('event_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=10, null=True)),
                ('impact_level', models.CharField(blank=True, max_length=10, null=True)),
                ('one_line_summary', models.TextField(blank=True, null=True)),
                ('key_entities', models.JSONField(default=list)),
                ('is_extracted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='pipeline_ne_publish_1da118_idx'), models.Index(fields=['impact_level'], name='pipeline_ne_impact__b6befe_idx'), models.Index(fields=['sentiment'], name='pipeline_ne_sentime_9d203a_idx'), models.Index(fields=['source_type'], name='pipeline_ne_source__5d2142_idx'), models.Index(fields=['is_extracted'], name='pipeline_ne_is_extr_fa5605_idx')],
            },
        ),
    ]
